version: '3.8'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    env_file: .env.prod
    depends_on:
      - prod-db
    volumes:
      - ./webapp:/opt/webapp
  dev-db:
    image: postgres:13
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest
    networks:
      - eeproperty
  test-db:
    image: postgres:13
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest
    networks:
      - eeproperty
  prod-db:
    image: postgres:13
    ports:
      - 5436:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest
    networks:
      - eeproperty
networks:
 eeproperty: